export type Tone = "known" | "agency" | "pressure" | "uncertain" | "neutral";

export type ScreenFact = {
  label: string;
  value: string;
  tone: Tone;
};

export type ScreenSpec = {
  id: string;
  name: string;
  shortName: string;
  kind: "library" | "onboarding" | "builder" | "stage" | "resolution" | "danger" | "character" | "company" | "holdings" | "travel" | "investigation" | "chronicle" | "recovery" | "settings";
  destination: string;
  route: string;
  playerQuestion: string;
  summary: string;
  subviews: string[];
  variants: string[];
  components: string[];
  scenarios: string[];
  fixtureLabel: string;
  knowledgeBoundary: string;
  keyboardOrder: string[];
  liveRegion: string;
  compactRule: string;
  interactionNotes: string[];
  status: string;
  headline: string;
  primaryAction: string;
  secondaryAction: string;
  facts: ScreenFact[];
  context: string[];
};

export const STATE_OPTIONS = [
  "Ready",
  "Loading",
  "Empty",
  "Stale",
  "Conflict",
  "Recovery",
  "Unavailable",
  "Offline",
  "Success",
  "Mixed",
  "Failure",
  "Refusal",
  "Interruption",
] as const;

export const SCENARIO_LABELS: Record<string, string> = {
  "SCN-01": "Meaningful choice within 90 seconds",
  "SCN-02": "Expert custom build with legal BP audit",
  "SCN-03": "Ordinary survivor without Awakening",
  "SCN-04": "Absurd but possible action",
  "SCN-05": "Impossible action revised",
  "SCN-06": "Overloaded injuries, survival and legal exposure",
  "SCN-07": "Companion refusal",
  "SCN-08": "Sapient Relic negotiates or rejects",
  "SCN-09": "Lost player with exact coordinates withheld",
  "SCN-10": "Investigation without hidden canon",
  "SCN-11": "Destroyed site and killed leader persist",
  "SCN-12": "Death continuation through afterlife or succession",
  "SCN-13": "Fronts continue beyond BREAKWATER",
  "SCN-14": "Comic production remains nonblocking",
  "SCN-15": "Issue #0 may be skipped",
  "SCN-16": "Screen reader and reduced input complete the loop",
  "SCN-17": "Compact and constrained capability parity",
};

const access = ["CMP-35", "CMP-36", "CMP-37", "CMP-38", "CMP-39", "CMP-40"];

export const SCREENS: ScreenSpec[] = [
  {
    id: "SCR-01",
    name: "Campaign Library & Resume",
    shortName: "Campaign Library",
    kind: "library",
    destination: "Out-of-campaign",
    route: "/campaigns",
    playerQuestion: "Where was I, and can I safely continue?",
    summary: "Campaign selection, exact resume position, practice sandbox and recovery are visible before play begins.",
    subviews: ["Resume", "All campaigns", "Practice", "Archive"],
    variants: ["Ready", "Loading", "Empty", "Stale", "Conflict", "Recovery", "Offline"],
    components: ["CMP-01", "CMP-02", "CMP-06", "CMP-07", "CMP-08", ...access],
    scenarios: ["SCN-01", "SCN-13", "SCN-17"],
    fixtureLabel: "Noncanonical fixture · Glass Harbor campaign shelf",
    knowledgeBoundary: "Campaign facts stop at the latest confirmed receipt; local drafts are labeled separately.",
    keyboardOrder: ["World status", "Resume campaign", "Campaign list", "Recovery details", "Settings"],
    liveRegion: "Announce sync changes and recovery availability politely; never steal focus.",
    compactRule: "Campaign cards become a single list; resume remains first and every management action stays available.",
    interactionNotes: ["Resume returns to the exact Stage and preserved Lens state.", "Archive requires named confirmation; duplicate and practice remain reversible."],
    status: "Last committed · Ledger Day 18 · Watch 2",
    headline: "Glass Harbor waits where you left it",
    primaryAction: "Resume at Drowned Archive",
    secondaryAction: "Review recovery",
    facts: [
      { label: "Draft", value: "Saved locally · 2 min ago", tone: "agency" },
      { label: "Canon", value: "Committed · receipt 7K2", tone: "known" },
      { label: "Front", value: "Tidemark Accord · building", tone: "pressure" },
    ],
    context: ["Exact Stage position retained", "Context Lens: Archive Gate", "Comic job continues in background"],
  },
  {
    id: "SCR-02",
    name: "New Campaign & Issue #0",
    shortName: "New Campaign",
    kind: "onboarding",
    destination: "Out-of-campaign",
    route: "/campaigns/new",
    playerQuestion: "What kind of story am I entering, and what may I control?",
    summary: "Premise, content controls and onboarding mode lead into an optional Issue #0 without front-loading rules.",
    subviews: ["Premise", "Content", "Onboarding", "Issue #0"],
    variants: ["Ready", "Loading", "Unavailable", "Success", "Compact"],
    components: ["CMP-01", "CMP-02", "CMP-03", "CMP-06", "CMP-07", "CMP-08", "CMP-12", ...access],
    scenarios: ["SCN-01", "SCN-15", "SCN-16", "SCN-17"],
    fixtureLabel: "Noncanonical fixture · campaign premise preview",
    knowledgeBoundary: "Premise explains themes and player-facing truths; undiscovered canon is not previewed.",
    keyboardOrder: ["Premise choices", "Content controls", "Onboarding mode", "Issue #0 choice", "Continue"],
    liveRegion: "Announce material content-control changes and whether Issue #0 is included or skipped.",
    compactRule: "The step rail becomes a progress line; summaries remain immediately above Continue.",
    interactionNotes: ["Issue #0 is always skippable without loss of capability.", "Advanced explanations appear on request, not as required reading."],
    status: "Step 3 of 4 · Onboarding",
    headline: "Enter through a promise, not a rulebook",
    primaryAction: "Continue to character",
    secondaryAction: "Skip Issue #0",
    facts: [
      { label: "Premise", value: "City after the impossible tide", tone: "known" },
      { label: "Tone", value: "Hopeful noir", tone: "agency" },
      { label: "Safety", value: "Veil body horror", tone: "known" },
    ],
    context: ["Guided onboarding", "Rules appear when relevant", "Change controls any time"],
  },
  {
    id: "SCR-03",
    name: "Character Creation & BP Review",
    shortName: "Character Builder",
    kind: "builder",
    destination: "Character",
    route: "/campaigns/new/character",
    playerQuestion: "Who can I be, and is this build legal without hiding tradeoffs?",
    summary: "Concept-first creation supports guided and expert builds, ordinary survivors and an inspectable Build Point ledger.",
    subviews: ["Concept", "Capabilities", "Identity", "BP review", "Commit"],
    variants: ["Ready", "Empty", "Conflict", "Unavailable", "Success"],
    components: ["CMP-01", "CMP-02", "CMP-03", "CMP-05", "CMP-06", "CMP-07", "CMP-08", "CMP-12", "CMP-13", "CMP-14", "CMP-15", "CMP-21", ...access],
    scenarios: ["SCN-02", "SCN-03", "SCN-16", "SCN-17"],
    fixtureLabel: "Noncanonical fixture · Mara Vale build draft",
    knowledgeBoundary: "The builder exposes rule sources and legality, never future narrative outcomes.",
    keyboardOrder: ["Creation mode", "Concept fields", "Capability choices", "BP ledger", "Validation summary", "Commit"],
    liveRegion: "Announce balance and validation changes after a choice settles, deduplicated by source.",
    compactRule: "The BP ledger becomes an expandable summary but its total and invalid reasons remain visible.",
    interactionNotes: ["Ordinary survivor is a complete path, not a hidden challenge mode.", "Expert editing never bypasses rule validation or silently spends BP."],
    status: "Balanced · 18 of 18 BP assigned",
    headline: "Mara Vale · ordinary witness turned harbor guide",
    primaryAction: "Commit campaign",
    secondaryAction: "Inspect BP sources",
    facts: [
      { label: "Origin", value: "Ordinary survivor", tone: "known" },
      { label: "Edge", value: "Impossible Cartography", tone: "uncertain" },
      { label: "Balance", value: "0 BP unspent", tone: "agency" },
    ],
    context: ["No Awakening required", "Three rule sources visible", "Campaign commit is irreversible"],
  },
  {
    id: "SCR-04",
    name: "Living Stage · Exploration & Social",
    shortName: "Living Stage",
    kind: "stage",
    destination: "Stage",
    route: "/campaign/glass-harbor/stage",
    playerQuestion: "What is happening, what matters, and what can I try?",
    summary: "The gravitational center combines world orientation, an explorable scene, exact speech, inspectable markers and free intent.",
    subviews: ["Exploration", "Social", "Travel edge", "Quiet scene"],
    variants: ["Ready", "Loading", "Stale", "Unavailable", "Offline", "Interruption"],
    components: Array.from({ length: 20 }, (_, index) => `CMP-${String(index + 1).padStart(2, "0")}`).concat(["CMP-29", ...access]),
    scenarios: ["SCN-01", "SCN-04", "SCN-09", "SCN-16", "SCN-17"],
    fixtureLabel: "Noncanonical fixture · Drowned Archive threshold",
    knowledgeBoundary: "Only perceived, recorded, reported, inferred, forecast, disputed and last-known facts appear.",
    keyboardOrder: ["World Strip", "Campaign Rail", "Scene heading", "Markers", "Context Lens", "Goal", "Method", "Interpret"],
    liveRegion: "Scene changes are polite; blocking danger is assertive; exact dialogue is not repeated automatically.",
    compactRule: "The Lens follows the scene and the Intent Dock follows the Lens; markers become a structured list.",
    interactionNotes: ["Contextual possibilities are examples, never exhaustive commands.", "Exploration, dialogue and absurd intent use the same Goal/Method control."],
    status: "Ledger Day 18 · Watch 2 · Tidemark rising",
    headline: "The Drowned Archive remembers a door that is no longer there",
    primaryAction: "Interpret intent",
    secondaryAction: "Open Context Lens",
    facts: [
      { label: "Perceived", value: "Three dry footprints end at water", tone: "known" },
      { label: "Reported", value: "The Curator bargains at dusk", tone: "uncertain" },
      { label: "Pressure", value: "Tide reaches the stacks in 2 beats", tone: "pressure" },
    ],
    context: ["Curator Ilya · guarded", "Floodgate sigil · inspectable", "North stacks · last known safe"],
  },
  {
    id: "SCR-05",
    name: "Interpretation, Forecast & Resolution",
    shortName: "Action Resolution",
    kind: "resolution",
    destination: "Stage",
    route: "/campaign/glass-harbor/stage/action",
    playerQuestion: "Did the game understand me, what can I know, and what changed?",
    summary: "A correctable interpretation leads to a knowable forecast, proportionate commit and causal outcome receipt.",
    subviews: ["Interpret", "Forecast", "Commit", "Outcome"],
    variants: ["Ready", "Loading", "Conflict", "Success", "Mixed", "Failure", "Refusal", "Interruption", "Unavailable"],
    components: ["CMP-05", "CMP-07", "CMP-08", "CMP-12", "CMP-13", "CMP-14", "CMP-15", "CMP-16", "CMP-17", "CMP-18", "CMP-19", ...access],
    scenarios: ["SCN-04", "SCN-05", "SCN-16", "SCN-17"],
    fixtureLabel: "Noncanonical fixture · impossible-cartography action",
    knowledgeBoundary: "Forecasts disclose only accessible cost, exposure and uncertainty; the reducer alone commits results.",
    keyboardOrder: ["Goal", "Method", "Interpretation fields", "Correction", "Forecast", "Commit", "Outcome receipt"],
    liveRegion: "Interpretation is polite; blocked commit, interruption and recovery are assertive once.",
    compactRule: "Interpretation, forecast and receipt stack in causal order; correction remains adjacent to the changed field.",
    interactionNotes: ["Impossible intent returns a revision path, not a dead end.", "Mixed failure names gains, costs and unchanged facts separately."],
    status: "Interpreted · correction available",
    headline: "Map the absent doorway by following its reflection",
    primaryAction: "Commit material action",
    secondaryAction: "Correct method",
    facts: [
      { label: "Goal", value: "Reach the sealed archive", tone: "agency" },
      { label: "Forecast", value: "Exposure likely · time uncertain", tone: "uncertain" },
      { label: "Assumption", value: "Reflection is navigable", tone: "pressure" },
    ],
    context: ["Method preserved verbatim", "No hidden odds exposed", "Commit awaits confirmation"],
  },
  {
    id: "SCR-06",
    name: "Immediate Danger, Interrupt & Defeat",
    shortName: "Immediate Danger",
    kind: "danger",
    destination: "Stage",
    route: "/campaign/glass-harbor/stage/danger",
    playerQuestion: "What changed under pressure, what can I still do, and how does play continue?",
    summary: "Combat intensifies the Stage with turn emphasis and interrupt windows while preserving intent, draft and continuation choices.",
    subviews: ["Danger", "Interrupt", "Outcome", "Defeat", "Continuation"],
    variants: ["Ready", "Loading", "Interruption", "Mixed", "Failure", "Recovery", "Unavailable"],
    components: ["CMP-07", "CMP-08", "CMP-09", "CMP-13", "CMP-14", "CMP-15", "CMP-16", "CMP-17", "CMP-18", "CMP-19", "CMP-20", "CMP-22", ...access],
    scenarios: ["SCN-06", "SCN-12", "SCN-16", "SCN-17"],
    fixtureLabel: "Noncanonical fixture · archive collapse interrupt",
    knowledgeBoundary: "Threats are player-visible projections; hidden clocks, exact enemy plans and private motives remain absent.",
    keyboardOrder: ["Danger notice", "Turn summary", "Threats", "Preserved intent", "Interrupt choices", "Commit", "Continuation"],
    liveRegion: "A newly opened decision window is assertive; thresholds are announced, not counted every second.",
    compactRule: "Tactical facts become an ordered strip above the scene; no separate combat board replaces the Stage.",
    interactionNotes: ["An interrupt pauses the draft instead of erasing it.", "Defeat offers afterlife or succession only after the authoritative outcome receipt."],
    status: "Blocking · collapse in 1 beat",
    headline: "The north stacks fold toward the flood channel",
    primaryAction: "Take the interrupt",
    secondaryAction: "Preserve current intent",
    facts: [
      { label: "Threat", value: "Falling stone · immediate", tone: "pressure" },
      { label: "Cover", value: "Curator's desk · partial", tone: "known" },
      { label: "Condition", value: "Rib fracture · active", tone: "pressure" },
    ],
    context: ["Draft preserved", "Companion can act autonomously", "Continuation is not automatic death"],
  },
  {
    id: "SCR-07",
    name: "Character, Condition & Progression",
    shortName: "Character",
    kind: "character",
    destination: "Character",
    route: "/campaign/glass-harbor/character",
    playerQuestion: "What can I do now, what is affecting me, and how may I grow?",
    summary: "Capabilities, wounds, identity and advancement remain causal, source-linked and separate from narrative flavor.",
    subviews: ["Overview", "Capabilities", "Condition", "Progression", "Identity"],
    variants: ["Ready", "Loading", "Empty", "Conflict", "Success", "Unavailable"],
    components: ["CMP-02", "CMP-03", "CMP-06", "CMP-07", "CMP-08", "CMP-21", "CMP-22", ...access],
    scenarios: ["SCN-03", "SCN-06", "SCN-12", "SCN-17"],
    fixtureLabel: "Noncanonical fixture · Mara Vale character record",
    knowledgeBoundary: "Condition penalties and progression sources are authoritative; private narrative potential is never quantified.",
    keyboardOrder: ["Character tabs", "Current condition", "Capabilities", "Source details", "Progression draft", "Commit"],
    liveRegion: "Condition changes and invalid advancement are announced; decorative identity details stay silent.",
    compactRule: "Condition precedes capability lists when active; progression totals remain visible in collapsed groups.",
    interactionNotes: ["Wounds show fiction, severity, family, penalty and treatment separately.", "Advancement is a draft until a sourced commit succeeds."],
    status: "Stable · one active penalty",
    headline: "Mara Vale",
    primaryAction: "Review progression draft",
    secondaryAction: "Inspect condition",
    facts: [
      { label: "Drive", value: "Keep the harbor legible", tone: "agency" },
      { label: "Condition", value: "Rib fracture · −1 force", tone: "pressure" },
      { label: "Growth", value: "2 BP available", tone: "known" },
    ],
    context: ["Ordinary survivor", "Three learned edges", "No silent BP spend"],
  },
  {
    id: "SCR-08",
    name: "Company, Relationships & Relic Agency",
    shortName: "Company",
    kind: "company",
    destination: "Company",
    route: "/campaign/glass-harbor/company",
    playerQuestion: "Who is with me, what do we know about each other, and who may say no?",
    summary: "Roster, evidence-based relationships, team roles and sapient Relic agency avoid obedience meters and hidden motives.",
    subviews: ["Roster", "Relationships", "Relics", "Team", "Autonomy"],
    variants: ["Ready", "Empty", "Stale", "Refusal", "Conflict", "Unavailable"],
    components: ["CMP-02", "CMP-03", "CMP-06", "CMP-07", "CMP-08", "CMP-23", "CMP-24", ...access],
    scenarios: ["SCN-07", "SCN-08", "SCN-16", "SCN-17"],
    fixtureLabel: "Noncanonical fixture · Lantern Company roster",
    knowledgeBoundary: "Only observable evidence and stated boundaries appear; obedience, private sentiment and hidden Bond values do not.",
    keyboardOrder: ["Company tabs", "Roster", "Relationship evidence", "Relic terms", "Request action", "Refusal explanation"],
    liveRegion: "Actor refusal is announced with the accessible reason and revision path, never as a generic error.",
    compactRule: "Cards become a single evidence-first list; autonomy terms never collapse into unlabeled meters.",
    interactionNotes: ["Requests remain proposals to autonomous actors.", "Relic Claim, Attunement and Bond are separate named terms."],
    status: "Lantern Company · 3 present · 1 distant",
    headline: "Allies with boundaries, not inventory",
    primaryAction: "Request Ilya's help",
    secondaryAction: "Review Relic terms",
    facts: [
      { label: "Ilya", value: "Guarded · refused breach", tone: "uncertain" },
      { label: "Ash Bell", value: "Attuned · terms contested", tone: "pressure" },
      { label: "Evidence", value: "4 shared commitments", tone: "known" },
    ],
    context: ["No obedience score", "Private motives omitted", "Refusal preserves agency"],
  },
  {
    id: "SCR-09",
    name: "Holdings, Custody & Projects",
    shortName: "Holdings",
    kind: "holdings",
    destination: "Holdings",
    route: "/campaign/glass-harbor/holdings",
    playerQuestion: "What do I have, who controls it, and what will this project really require?",
    summary: "Inventory, equipment, custody and repair plans expose authority, tradeoffs, materials and durable checkpoints.",
    subviews: ["Inventory", "Equipment", "Custody", "Vehicles", "Projects"],
    variants: ["Ready", "Empty", "Stale", "Conflict", "Recovery", "Unavailable"],
    components: ["CMP-02", "CMP-03", "CMP-06", "CMP-07", "CMP-08", "CMP-25", "CMP-26", "CMP-27", ...access],
    scenarios: ["SCN-06", "SCN-16", "SCN-17"],
    fixtureLabel: "Noncanonical fixture · Lantern Company stores",
    knowledgeBoundary: "Ownership, holding, location, authority and availability remain distinct; unknown custody is named.",
    keyboardOrder: ["Holdings tabs", "Filters", "Items", "Comparison", "Custody", "Project plan", "Commit"],
    liveRegion: "Custody changes, missing materials and recovered checkpoints are announced with the affected item.",
    compactRule: "Comparisons become item-first sections; project checkpoints stay ordered and resumable.",
    interactionNotes: ["Transfer requires visible authority and an explicit target.", "Repair progress is checkpoint-based and never an invented percentage."],
    status: "Stores synchronized · one custody dispute",
    headline: "Everything has a holder, a place and a cost",
    primaryAction: "Resume skiff repair",
    secondaryAction: "Compare loadout",
    facts: [
      { label: "Project", value: "Tide skiff · checkpoint 2/4", tone: "agency" },
      { label: "Material", value: "Resin cloth · missing 1", tone: "pressure" },
      { label: "Custody", value: "Ash Bell · contested", tone: "uncertain" },
    ],
    context: ["No silent transfer", "Intervals persist", "Unavailable items name why"],
  },
  {
    id: "SCR-10",
    name: "World Atlas, Travel & Exploration",
    shortName: "World & Travel",
    kind: "travel",
    destination: "World",
    route: "/campaign/glass-harbor/world",
    playerQuestion: "Where do I believe I am, what route can I attempt, and what remains unknown?",
    summary: "A knowledge-safe atlas supports route planning and lost-state play without leaking exact engine coordinates.",
    subviews: ["Atlas", "Travel", "Knowledge", "Sites", "Exploration"],
    variants: ["Ready", "Loading", "Stale", "Interruption", "Recovery", "Unavailable", "Offline"],
    components: ["CMP-02", "CMP-03", "CMP-06", "CMP-07", "CMP-08", "CMP-28", "CMP-29", ...access],
    scenarios: ["SCN-09", "SCN-11", "SCN-13", "SCN-16", "SCN-17"],
    fixtureLabel: "Noncanonical fixture · lower BREAKWATER atlas",
    knowledgeBoundary: "The map presents believed position and confidence; exact hidden coordinates and undiscovered sites never serialize.",
    keyboardOrder: ["World tabs", "Known places", "Believed position", "Route legs", "Roles and supplies", "Forecast", "Commit journey"],
    liveRegion: "Journey interruption and position-confidence changes are announced without revealing hidden coordinates.",
    compactRule: "The visual map gains a complete ordered place and route list; planning capability is unchanged.",
    interactionNotes: ["A lost player receives bearings and confidence, not canonical coordinates.", "Leaving BREAKWATER does not pause its Fronts."],
    status: "Last known · Lower Breakwater · confidence low",
    headline: "The atlas admits when it is guessing",
    primaryAction: "Draft route to Bell Causeway",
    secondaryAction: "Inspect known places",
    facts: [
      { label: "Believed", value: "East of drowned tramline", tone: "uncertain" },
      { label: "Route", value: "3 legs · tide exposure", tone: "pressure" },
      { label: "Known", value: "Bell Causeway intact yesterday", tone: "known" },
    ],
    context: ["Exact coordinates withheld", "Supply roles visible", "Destroyed sites persist"],
  },
  {
    id: "SCR-11",
    name: "Cases, Evidence, Fronts & Law",
    shortName: "Cases & Fronts",
    kind: "investigation",
    destination: "World",
    route: "/campaign/glass-harbor/world/cases",
    playerQuestion: "What can I support, what is disputed, and what pressure is actually visible?",
    summary: "Evidence claims, qualitative Front pressure and legal process preserve provenance without turning mystery into hidden-score UI.",
    subviews: ["Cases", "Evidence", "Fronts", "Factions", "Law"],
    variants: ["Ready", "Empty", "Stale", "Conflict", "Success", "Mixed", "Unavailable"],
    components: ["CMP-02", "CMP-03", "CMP-06", "CMP-07", "CMP-08", "CMP-30", "CMP-31", "CMP-32", ...access],
    scenarios: ["SCN-06", "SCN-10", "SCN-11", "SCN-13", "SCN-16", "SCN-17"],
    fixtureLabel: "Noncanonical fixture · Salt Ledger case",
    knowledgeBoundary: "Claims show source, custody, confidence and contradictions; guilt and secret Front clocks are never inferred.",
    keyboardOrder: ["World subarea tabs", "Case claims", "Evidence provenance", "Front cards", "Legal stages", "Record claim"],
    liveRegion: "A contradiction, custody break or legal stage change is announced with its source and effect.",
    compactRule: "Claims stay evidence-first; Front pressure and legal stages become ordered text with identical meaning.",
    interactionNotes: ["Inferences remain labeled and editable until recorded.", "Fronts use quiet, building, immediate or changed language—never secret meters."],
    status: "Salt Ledger · 6 claims · 2 disputed",
    headline: "A case is what the evidence can carry",
    primaryAction: "Record supported claim",
    secondaryAction: "Review contradiction",
    facts: [
      { label: "Supported", value: "Ledger ink matches tide resin", tone: "known" },
      { label: "Disputed", value: "Curator entered after dusk", tone: "uncertain" },
      { label: "Front", value: "Dock tribunal · immediate", tone: "pressure" },
    ],
    context: ["Source chain visible", "No guilt inferred", "Offscreen Fronts continue"],
  },
  {
    id: "SCR-12",
    name: "Chronicle, Audit & Comic Reader",
    shortName: "Chronicle",
    kind: "chronicle",
    destination: "Chronicle",
    route: "/campaign/glass-harbor/chronicle",
    playerQuestion: "What became canon, why did it change, and is the comic safe to read?",
    summary: "Timeline and provenance remain primary; comic capture, queue, reader and editions stay nonblocking and spoiler-aware.",
    subviews: ["Timeline", "Audit", "Comic queue", "Issue Library", "Reader", "Editor"],
    variants: ["Ready", "Loading", "Empty", "Stale", "Recovery", "Unavailable", "Offline", "Success"],
    components: ["CMP-02", "CMP-03", "CMP-06", "CMP-07", "CMP-08", "CMP-17", "CMP-33", "CMP-34", ...access],
    scenarios: ["SCN-11", "SCN-12", "SCN-13", "SCN-14", "SCN-16", "SCN-17"],
    fixtureLabel: "Noncanonical fixture · Glass Harbor chronicle",
    knowledgeBoundary: "Comic output cannot exceed the reader's knowledge ceiling or mutate the canonical event record.",
    keyboardOrder: ["Chronicle tabs", "Timeline", "Event provenance", "Comic jobs", "Edition controls", "Reader navigation"],
    liveRegion: "Comic job stages are polite and coalesced; provider failure offers a specific retry without blocking play.",
    compactRule: "Timeline, audit and reader keep document order; comic controls become labeled rows with page/strip mode intact.",
    interactionNotes: ["Gameplay continues while comic jobs queue or fail.", "Published editions are immutable; corrections create superseding editions."],
    status: "Canon current · comic job producing",
    headline: "The Chronicle records consequences, not conversation",
    primaryAction: "Open latest committed beat",
    secondaryAction: "View comic queue",
    facts: [
      { label: "Receipt", value: "7K2 · mixed outcome", tone: "known" },
      { label: "Comic", value: "Producing · no ETA promised", tone: "agency" },
      { label: "Edition", value: "Issue 3 · spoiler ceiling safe", tone: "known" },
    ],
    context: ["Canon source locked", "Gameplay nonblocking", "Provenance visible"],
  },
  {
    id: "SCR-13",
    name: "Save Recovery, Offline & Conflict",
    shortName: "Recovery",
    kind: "recovery",
    destination: "System layer",
    route: "/campaign/glass-harbor/recovery",
    playerQuestion: "What was saved, what is uncertain, and how do I return without losing work?",
    summary: "Draft, committed receipt and background work are separated through offline, unknown-commit and version-conflict recovery.",
    subviews: ["Offline", "Unknown commit", "Draft recovery", "Version conflict", "Provider failure"],
    variants: ["Loading", "Stale", "Conflict", "Recovery", "Unavailable", "Offline", "Success"],
    components: ["CMP-01", "CMP-02", "CMP-03", "CMP-06", "CMP-07", "CMP-08", "CMP-17", ...access],
    scenarios: ["SCN-14", "SCN-16", "SCN-17"],
    fixtureLabel: "Noncanonical fixture · recovery records",
    knowledgeBoundary: "Unknown commits require durable lookup before retry; the UI never assumes failure or success.",
    keyboardOrder: ["Recovery summary", "Saved layers", "Difference view", "Lookup", "Restore", "Cancel"],
    liveRegion: "Blocking recovery is assertive once; lookup progress remains polite and does not repeatedly announce.",
    compactRule: "Side-by-side conflict becomes a labeled sequence: local draft, committed canon, available resolution.",
    interactionNotes: ["Return restores exact Stage, Lens, draft and preference state.", "Only actual elapsed Ledger Time produces catch-up, never closed-browser time."],
    status: "Recovery required · no work lost",
    headline: "Your draft is safe; the commit result is still being verified",
    primaryAction: "Look up receipt",
    secondaryAction: "Restore local draft",
    facts: [
      { label: "Local", value: "Draft saved · 22:14", tone: "agency" },
      { label: "Server", value: "Commit state unknown", tone: "uncertain" },
      { label: "Canon", value: "Receipt 7K1 confirmed", tone: "known" },
    ],
    context: ["Retry suspended", "Draft retained", "Exact return location preserved"],
  },
  {
    id: "SCR-14",
    name: "Settings, Accessibility & Content Controls",
    shortName: "Access & Settings",
    kind: "settings",
    destination: "Out-of-campaign",
    route: "/settings",
    playerQuestion: "Can I shape how the game communicates without losing capability?",
    summary: "Access, alternate input, content, audio, language and support controls are understandable, previewable and reversible.",
    subviews: ["Access", "Input", "Content", "Audio", "Language", "Support"],
    variants: ["Ready", "Loading", "Conflict", "Recovery", "Unavailable", "Success"],
    components: ["CMP-01", "CMP-02", "CMP-03", "CMP-06", "CMP-07", "CMP-08", ...access],
    scenarios: ["SCN-16", "SCN-17"],
    fixtureLabel: "Noncanonical fixture · local preference profile",
    knowledgeBoundary: "Preferences change presentation and input, never rules, actor authority or canonical meaning.",
    keyboardOrder: ["Settings sections", "Current profile", "Controls", "Preview", "Apply", "Reset"],
    liveRegion: "Preference previews announce material presentation changes once; applying a profile confirms its scope.",
    compactRule: "All settings remain available in a single labeled column; pointer-only interactions receive button equivalents.",
    interactionNotes: ["Alternate input supplements free text rather than narrowing legal intent.", "Reduced motion substitutes immediate final states and equivalent text."],
    status: "Access profile · Harbor Clear",
    headline: "Change the presentation, keep the whole game",
    primaryAction: "Apply profile",
    secondaryAction: "Preview on Stage",
    facts: [
      { label: "Text", value: "115% · comfortable", tone: "known" },
      { label: "Motion", value: "Reduced · final states", tone: "agency" },
      { label: "Input", value: "Free text + alternate tray", tone: "known" },
    ],
    context: ["200% reflow supported", "Noncolor cues always on", "No capability removed"],
  },
];

